version: "3.8"
services:
  backend:
    build: ./
    ports:
      - "8012:8012"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - PORT=8012
      - NODE_ENV=production
      - CDN_BASE_UPLOAD_URL
      - CDN_BASE_ACCESS_URL
      - CDN_API_KEY
      - POSTMARK_USERNAME
      - BUNNY_LIBRARY_ID
      - BUNNY_STREAM_API_KEY
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
    restart: always
